using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;

namespace VERA.Registry.Models
{
    public class RegistryIssuer
    {
        public int RegistryIssuerId { get; set; }

        // Generated by VERA - user does not enter this
        [ValidateNever]
        [Display(Name = "VERA Issuer ID")]
        public string VeraIssuerId { get; set; } = string.Empty;

        [Required]
        [Display(Name = "Legal Business Name")]
        public string LegalName { get; set; } = string.Empty;

        [Required]
        [Display(Name = "CIPC Registration Number")]
        public string CIPCRegistrationNumber { get; set; } = string.Empty;

        [Display(Name = "Trading Name")]
        public string? TradingName { get; set; }

        [Display(Name = "VAT Number")]
        public string? VATNumber { get; set; }

        // Set by our prototype logic
        public bool CIPCVerified { get; set; }

        public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

        public ICollection<RegisteredPurchaseOrder> PurchaseOrders { get; set; }
            = new List<RegisteredPurchaseOrder>();
    }
}