using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;

namespace VERA.Registry.Models
{
    public class RegisteredPurchaseOrder
    {
        public int RegisteredPurchaseOrderId { get; set; }

        // Generated by VERA
        [ValidateNever]
        [Display(Name = "VERA PO ID")]
        public string VeraPOId { get; set; } = string.Empty;

        [Range(1, int.MaxValue,
            ErrorMessage = "Please select an issuing business.")]
        [Display(Name = "Issuing Business")]
        public int RegistryIssuerId { get; set; }

        public RegistryIssuer? RegistryIssuer { get; set; }

        [Required]
        [Display(Name = "PO Number")]
        public string PONumber { get; set; } = string.Empty;

        [Required]
        [Display(Name = "Supplier Name")]
        public string SupplierName { get; set; } = string.Empty;

        [Display(Name = "Supplier CIPC Registration")]
        public string? SupplierCIPCRegistrationNumber { get; set; }

        [Required]
        [Column(TypeName = "decimal(18,2)")]
        [Display(Name = "PO Value")]
        public decimal POValue { get; set; }

        [Required]
        [Display(Name = "Issue Date")]
        [DataType(DataType.Date)]
        public DateTime IssueDate { get; set; }

        [Display(Name = "Delivery Date")]
        [DataType(DataType.Date)]
        public DateTime? DeliveryDate { get; set; }

        [Display(Name = "Delivery Address")]
        public string? DeliveryAddress { get; set; }

        [Display(Name = "Payment Terms")]
        public string? PaymentTerms { get; set; }

        // Set internally by VERA
        [ValidateNever]
        public string Status { get; set; } = "ACTIVE";

        // Generated internally by VERA
        [ValidateNever]
        public string CanonicalFingerprint { get; set; } = string.Empty;

        public DateTime RegisteredAt { get; set; } = DateTime.UtcNow;

        public DateTime UpdatedAt { get; set; } = DateTime.UtcNow;

        public ICollection<FinancingClaim> FinancingClaims { get; set; }
            = new List<FinancingClaim>();
        public ICollection<PurchaseOrderDocument> Documents { get; set; }
    = new List<PurchaseOrderDocument>();
    }
}