// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VERA.Registry.Data;

#nullable disable

namespace VERA.Registry.Migrations
{
    [DbContext(typeof(RegistryDbContext))]
    partial class RegistryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VERA.Registry.Models.FinancingClaim", b =>
                {
                    b.Property<int>("FinancingClaimId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FinancingClaimId"));

                    b.Property<string>("ClaimReference")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("RegisteredPurchaseOrderId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReleasedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FinancingClaimId");

                    b.HasIndex("RegisteredPurchaseOrderId");

                    b.ToTable("FinancingClaims");
                });

            modelBuilder.Entity("VERA.Registry.Models.PurchaseOrderDocument", b =>
                {
                    b.Property<int>("PurchaseOrderDocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PurchaseOrderDocumentId"));

                    b.Property<bool?>("AmountMatchesRegistry")
                        .HasColumnType("bit");

                    b.Property<string>("AnalysisNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AnalysisResult")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocumentHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal?>("ExtractedAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ExtractedPONumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCurrentVersion")
                        .HasColumnType("bit");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("PONumberMatchesRegistry")
                        .HasColumnType("bit");

                    b.Property<int>("RegisteredPurchaseOrderId")
                        .HasColumnType("int");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("int");

                    b.HasKey("PurchaseOrderDocumentId");

                    b.HasIndex("DocumentHash");

                    b.HasIndex("RegisteredPurchaseOrderId");

                    b.ToTable("PurchaseOrderDocuments");
                });

            modelBuilder.Entity("VERA.Registry.Models.RegisteredPurchaseOrder", b =>
                {
                    b.Property<int>("RegisteredPurchaseOrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RegisteredPurchaseOrderId"));

                    b.Property<string>("CanonicalFingerprint")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeliveryAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PONumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("POValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PaymentTerms")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("RegistryIssuerId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupplierCIPCRegistrationNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("VeraPOId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("RegisteredPurchaseOrderId");

                    b.HasIndex("VeraPOId")
                        .IsUnique();

                    b.HasIndex("RegistryIssuerId", "PONumber")
                        .IsUnique();

                    b.ToTable("RegisteredPurchaseOrders");
                });

            modelBuilder.Entity("VERA.Registry.Models.RegistryIssuer", b =>
                {
                    b.Property<int>("RegistryIssuerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RegistryIssuerId"));

                    b.Property<string>("CIPCRegistrationNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("CIPCVerified")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LegalName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TradingName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VATNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VeraIssuerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("RegistryIssuerId");

                    b.HasIndex("CIPCRegistrationNumber")
                        .IsUnique();

                    b.HasIndex("VeraIssuerId")
                        .IsUnique();

                    b.ToTable("RegistryIssuers");
                });

            modelBuilder.Entity("VERA.Registry.Models.FinancingClaim", b =>
                {
                    b.HasOne("VERA.Registry.Models.RegisteredPurchaseOrder", "RegisteredPurchaseOrder")
                        .WithMany("FinancingClaims")
                        .HasForeignKey("RegisteredPurchaseOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RegisteredPurchaseOrder");
                });

            modelBuilder.Entity("VERA.Registry.Models.PurchaseOrderDocument", b =>
                {
                    b.HasOne("VERA.Registry.Models.RegisteredPurchaseOrder", "RegisteredPurchaseOrder")
                        .WithMany("Documents")
                        .HasForeignKey("RegisteredPurchaseOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RegisteredPurchaseOrder");
                });

            modelBuilder.Entity("VERA.Registry.Models.RegisteredPurchaseOrder", b =>
                {
                    b.HasOne("VERA.Registry.Models.RegistryIssuer", "RegistryIssuer")
                        .WithMany("PurchaseOrders")
                        .HasForeignKey("RegistryIssuerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RegistryIssuer");
                });

            modelBuilder.Entity("VERA.Registry.Models.RegisteredPurchaseOrder", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("FinancingClaims");
                });

            modelBuilder.Entity("VERA.Registry.Models.RegistryIssuer", b =>
                {
                    b.Navigation("PurchaseOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
