using VERA.Models.Entities;
using VERA.Models.Enums;
using VERA.Models.Enums.VERA.Models.Enums;

namespace VERA.Business.Services
{
    /// <summary>
    /// Determines the final readiness status of an opportunity
    /// after verification, duplicate checks, fulfilment assessment
    /// and financial viability checks have been completed.
    ///
    /// This service does not make a lending decision.
    /// It determines whether an opportunity is ready to be reviewed
    /// by a funding partner, requires manual review, or should be blocked.
    /// </summary>
    public class OpportunityDecisionService
    {
        /// <summary>
        /// Evaluates all available verification results and risk flags
        /// and returns the appropriate VERA opportunity status.
        /// </summary>
        /// <param name="opportunity">
        /// The opportunity being assessed.
        /// </param>
        /// <param name="verificationResults">
        /// The explainable verification results generated by VERA.
        /// </param>
        /// <param name="riskFlags">
        /// The fulfilment and risk indicators identified by VERA.
        /// </param>
        /// <returns>
        /// The status that should be assigned to the opportunity.
        /// </returns>
        public OpportunityStatus Decide(
            Opportunity opportunity,
            IEnumerable<VerificationResult> verificationResults,
            IEnumerable<RiskFlag> riskFlags)
        {
            // Convert the incoming collections into lists so that
            // we can evaluate them multiple times efficiently.
            List<VerificationResult> verifications =
                verificationResults.ToList();

            List<RiskFlag> risks =
                riskFlags.ToList();

            // ---------------------------------------------------------
            // RULE 1: BLOCK CRITICAL VERIFICATION FAILURES
            // ---------------------------------------------------------
            //
            // If any verification check has completely failed,
            // the opportunity should not proceed to funding review.
            //
            // Example:
            // - invalid PO data
            // - failed identity check
            // - confirmed duplicate financing issue
            bool hasFailedVerification =
                verifications.Any(v =>
                    v.Status == VerificationStatus.Failed);

            if (hasFailedVerification)
            {
                return OpportunityStatus.Blocked;
            }

            // ---------------------------------------------------------
            // RULE 2: BLOCK CRITICAL RISK FLAGS
            // ---------------------------------------------------------
            //
            // Critical risk flags represent issues serious enough
            // to stop the opportunity from progressing automatically.
            bool hasCriticalRisk =
                risks.Any(r =>
                    r.Severity == RiskSeverity.Critical);

            if (hasCriticalRisk)
            {
                return OpportunityStatus.Blocked;
            }

            // ---------------------------------------------------------
            // RULE 3: MANUAL REVIEW FOR FLAGGED VERIFICATIONS
            // ---------------------------------------------------------
            //
            // A flagged verification does not automatically mean fraud.
            // It indicates that additional evidence or human review
            // may be required before the opportunity can proceed.
            bool hasFlaggedVerification =
                verifications.Any(v =>
                    v.Status == VerificationStatus.Flagged);

            if (hasFlaggedVerification)
            {
                return OpportunityStatus.ManualReview;
            }

            // ---------------------------------------------------------
            // RULE 4: MANUAL REVIEW FOR HIGH RISK
            // ---------------------------------------------------------
            //
            // High-risk indicators such as a very large jump in contract
            // size should not automatically block an SME.
            //
            // Instead, the opportunity should be escalated for human review.
            bool hasHighRisk =
                risks.Any(r =>
                    r.Severity == RiskSeverity.High);

            if (hasHighRisk)
            {
                return OpportunityStatus.ManualReview;
            }

            // ---------------------------------------------------------
            // RULE 5: FINANCIAL VIABILITY
            // ---------------------------------------------------------
            //
            // If the opportunity produces no positive remaining margin
            // after estimated fulfilment and funding costs, then VERA
            // should not describe it as finance-ready.
            if (opportunity.RemainingMargin <= 0)
            {
                return OpportunityStatus.ManualReview;
            }

            // ---------------------------------------------------------
            // RULE 6: FUNDING GAP
            // ---------------------------------------------------------
            //
            // If the funding gap is zero, the SME may not require
            // external fulfilment finance at all.
            //
            // For the MVP, the opportunity can still be considered
            // verified, but it should not automatically enter funding review.
            if (opportunity.FundingGap <= 0)
            {
                return OpportunityStatus.VerificationComplete;
            }

            // ---------------------------------------------------------
            // RULE 7: FINANCE READY
            // ---------------------------------------------------------
            //
            // If the opportunity has:
            // - no failed verifications
            // - no critical risks
            // - no flagged verifications
            // - no high-risk indicators
            // - a positive margin
            // - a real funding requirement
            //
            // then VERA considers the opportunity finance-ready.
            return OpportunityStatus.FinanceReady;
        }
    }
}