// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VERA.Data.Context;

#nullable disable

namespace VERA.Data.Migrations
{
    [DbContext(typeof(VeraDbContext))]
    [Migration("20260904231431_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VERA.Models.Entities.Business", b =>
                {
                    b.Property<int>("BusinessId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BusinessId"));

                    b.Property<bool>("BankAccountVerified")
                        .HasColumnType("bit");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Industry")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("YearsOperating")
                        .HasColumnType("int");

                    b.HasKey("BusinessId");

                    b.HasIndex("RegistrationNumber");

                    b.ToTable("Businesses");
                });

            modelBuilder.Entity("VERA.Models.Entities.FulfilmentRecord", b =>
                {
                    b.Property<int>("FulfilmentRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FulfilmentRecordId"));

                    b.Property<DateTime?>("ActualDeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("BuyerAcceptedDelivery")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("BuyerPaidDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DeliveredOnTime")
                        .HasColumnType("bit");

                    b.Property<bool>("DisputeOccurred")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FundedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("FunderSettled")
                        .HasColumnType("bit");

                    b.Property<int>("OpportunityId")
                        .HasColumnType("int");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FulfilmentRecordId");

                    b.HasIndex("OpportunityId")
                        .IsUnique();

                    b.ToTable("FulfilmentRecords");
                });

            modelBuilder.Entity("VERA.Models.Entities.FundingOffer", b =>
                {
                    b.Property<int>("FundingOfferId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FundingOfferId"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FunderName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("FundingCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsAccepted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsIllustrative")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OpportunityId")
                        .HasColumnType("int");

                    b.Property<int>("TermDays")
                        .HasColumnType("int");

                    b.HasKey("FundingOfferId");

                    b.HasIndex("OpportunityId");

                    b.ToTable("FundingOffers");
                });

            modelBuilder.Entity("VERA.Models.Entities.Opportunity", b =>
                {
                    b.Property<int>("OpportunityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OpportunityId"));

                    b.Property<int>("BusinessId")
                        .HasColumnType("int");

                    b.Property<string>("BuyerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BuyerReference")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("EstimatedFundingCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("FulfilmentCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FundingGap")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PONumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("POValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PlatformFee")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("RemainingMargin")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("RemainingMarginPercentage")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal>("SMEContribution")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("UploadedPOFileName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OpportunityId");

                    b.HasIndex("BusinessId");

                    b.HasIndex("Fingerprint");

                    b.HasIndex("PONumber");

                    b.ToTable("Opportunities");
                });

            modelBuilder.Entity("VERA.Models.Entities.RiskFlag", b =>
                {
                    b.Property<int>("RiskFlagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RiskFlagId"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OpportunityId")
                        .HasColumnType("int");

                    b.Property<int>("Severity")
                        .HasColumnType("int");

                    b.HasKey("RiskFlagId");

                    b.HasIndex("OpportunityId");

                    b.ToTable("RiskFlags");
                });

            modelBuilder.Entity("VERA.Models.Entities.VerificationResult", b =>
                {
                    b.Property<int>("VerificationResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VerificationResultId"));

                    b.Property<DateTime>("CheckedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Evidence")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsSimulated")
                        .HasColumnType("bit");

                    b.Property<int>("OpportunityId")
                        .HasColumnType("int");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("VerificationType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VerificationResultId");

                    b.HasIndex("OpportunityId");

                    b.ToTable("VerificationResults");
                });

            modelBuilder.Entity("VERA.Models.Entities.FulfilmentRecord", b =>
                {
                    b.HasOne("VERA.Models.Entities.Opportunity", "Opportunity")
                        .WithOne("FulfilmentRecord")
                        .HasForeignKey("VERA.Models.Entities.FulfilmentRecord", "OpportunityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Opportunity");
                });

            modelBuilder.Entity("VERA.Models.Entities.FundingOffer", b =>
                {
                    b.HasOne("VERA.Models.Entities.Opportunity", "Opportunity")
                        .WithMany("FundingOffers")
                        .HasForeignKey("OpportunityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Opportunity");
                });

            modelBuilder.Entity("VERA.Models.Entities.Opportunity", b =>
                {
                    b.HasOne("VERA.Models.Entities.Business", "Business")
                        .WithMany("Opportunities")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Business");
                });

            modelBuilder.Entity("VERA.Models.Entities.RiskFlag", b =>
                {
                    b.HasOne("VERA.Models.Entities.Opportunity", "Opportunity")
                        .WithMany("RiskFlags")
                        .HasForeignKey("OpportunityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Opportunity");
                });

            modelBuilder.Entity("VERA.Models.Entities.VerificationResult", b =>
                {
                    b.HasOne("VERA.Models.Entities.Opportunity", "Opportunity")
                        .WithMany("VerificationResults")
                        .HasForeignKey("OpportunityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Opportunity");
                });

            modelBuilder.Entity("VERA.Models.Entities.Business", b =>
                {
                    b.Navigation("Opportunities");
                });

            modelBuilder.Entity("VERA.Models.Entities.Opportunity", b =>
                {
                    b.Navigation("FulfilmentRecord");

                    b.Navigation("FundingOffers");

                    b.Navigation("RiskFlags");

                    b.Navigation("VerificationResults");
                });
#pragma warning restore 612, 618
        }
    }
}
